{"name": "test_false1", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_false1():\n>       assert False\nE       assert False\n\ntest_fail.py:2: AssertionError"}, "start": 1684331268594, "stop": 1684331268594, "uuid": "250fe3bf-a7ac-444a-88e5-3edd1c731bb0", "historyId": "6eba36055937aaa2f3d50322608cb1eb", "testCaseId": "6eba36055937aaa2f3d50322608cb1eb", "fullName": "test_fail#test_false1", "labels": [{"name": "suite", "value": "test_fail"}, {"name": "host", "value": "WIN-RURI6UF5EKD"}, {"name": "thread", "value": "8092-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_fail"}]}