{"name": "test_false2", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_false2():\n>       assert False\nE       assert False\n\ntest_fail.py:6: AssertionError"}, "start": 1684331268642, "stop": 1684331268643, "uuid": "a8734f3a-b5d7-4797-90eb-5a4165a04209", "historyId": "c1f391a364272476e1c421c0fa50c61c", "testCaseId": "c1f391a364272476e1c421c0fa50c61c", "fullName": "test_fail#test_false2", "labels": [{"name": "suite", "value": "test_fail"}, {"name": "host", "value": "WIN-RURI6UF5EKD"}, {"name": "thread", "value": "8092-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_fail"}]}